[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@layerzerolabs/lz-evm-oapp-v2/=node_modules/@layerzerolabs/lz-evm-oapp-v2/",
    "@layerzerolabs/lz-evm-protocol-v2/=node_modules/@layerzerolabs/lz-evm-protocol-v2/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@layerzerolabs/lz-evm-messagelib-v2/=node_modules/@layerzerolabs/lz-evm-messagelib-v2/",
    "solidity-bytes-utils/contracts/=lib/solidity-bytes-utils/contracts/"


]
[rpc_endpoints]
holesky = "https://ethereum-holesky-rpc.publicnode.com"
amoy = "https://polygon-amoy-bor-rpc.publicnode.com"
[etherscan]
holesky = { key = "WY4F1JEZT6T364HA9N7R8SANWEEMVY6AP3" }
amoy = { key = "BBTE2Q5FRZWFNIQY53PJGZTVVJFR1EYQFW" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
